server:
  port: 8080
  address: 0.0.0.0
  max-http-header-size: 16384
  servlet:
    context-path: /random-number-generator
spring:
  application:
    name: Random Number Generator Backend Application