server:
  port: 8081
  address: 0.0.0.0
  max-http-header-size: 16384
  servlet:
    context-path: /random-number-generator
spring:
  application:
    name: Random Number Generator Backend Application

random-number-generator:
  scheduled:
    generate-every-milliseconds: 10000
  range:
    min: 1  # Minimum value must be an integer in the [-1000000000,1000000000] interval
    max: 1000000000 # Maximum value must be an integer in the [-1000000000,1000000000] interval
  operator: +  # Supported values for this parameter: + - / *